on:
  pull_request:
    types: [opened, synchronize]
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare repository
        run: git fetch --tags
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm ci:test
      - run: npm ci:build
      - run: npm run package
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx auto shipit -d
